events {}

http {
  upstream model_upstream {
    server model-v1:8000;
    server model-v2:8000 backup;
  }

  server {
    listen 8080;

    location /health { proxy_pass http://model_upstream/health; }
    location /predict { proxy_pass http://model_upstream/predict; }
  }
}
